apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lti-example-tool
resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
images:
  - name: ghcr.io/simon-initiative/lti-example-tool
    newName: ghcr.io/simon-initiative/lti-example-tool
    newTag: latest
