services:
  app:
    image: ghcr.io/simon-initiative/lti-example-tool:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      ENV: prod
      SECRET_KEY_BASE: secret
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/lti_example_tool
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
