name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: lti_example_tool_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d lti_example_tool_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/lti_example_tool_test
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.14.0"
          rebar3-version: "3"
          elixir-version: "1.18.3"
      - run: gleam deps download
      - run: gleam build
      - run: gleam run -m lti_example_tool/database/migrate_and_seed test.setup
      - run: gleam test
      - run: gleam format --check src test
