name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 🗄 Start test database
        run: docker compose up -d postgres

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.10.0"
          rebar3-version: "3"
          # elixir-version: "1"
      - run: gleam deps download
      - run: gleam run -m lti_example_tool/database/migrate_and_seed test.reset
      - run: gleam test
      - run: gleam format --check src test
